# Generated by Django 4.2.6 on 2023-10-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreDepartamento",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nombre Departamento"
                    ),
                ),
                (
                    "siglaDepartamento",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Sigla Departamento"
                    ),
                ),
                (
                    "activoDepartamento",
                    models.BooleanField(default=False, verbose_name="active"),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["nombreDepartamento"],
                "unique_together": {("nombreDepartamento", "siglaDepartamento")},
            },
        ),
    ]
