# Generated by Django 4.2.6 on 2023-10-27 23:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("departamento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habilidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "habilidad",
                    models.CharField(max_length=50, verbose_name="Habilidad"),
                ),
            ],
            options={
                "verbose_name": "Habilidad",
                "verbose_name_plural": "Habilidades",
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=50, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=50, verbose_name="Apellidos"),
                ),
                (
                    "trabajo",
                    models.CharField(
                        choices=[
                            (0, "Contador"),
                            (1, "Administrador"),
                            (2, "Economista"),
                            (3, "Ingeniero"),
                            (4, "Desarrollador"),
                        ],
                        max_length=1,
                        verbose_name="Trabajo",
                    ),
                ),
                ("hv", ckeditor.fields.RichTextField(blank=True, default="None")),
                ("avatar", models.ImageField(blank=True, default="None", upload_to="")),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departamento.departamento",
                    ),
                ),
                ("habilidades", models.ManyToManyField(to="empleado.habilidades")),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
            },
        ),
    ]
